### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by oxr463**
Closes: https://github.com/proot-me/proot-rs/issues/18

### CODE REVIEW

**Comment by KB5201314** [comment]
Is this Dockerfile used to test proot-rs? And is it related to https://github.com/proot-me/proot-rs/issues/6#issuecomment-846402777 ?

**Comment by oxr463** [comment]
> Is this Dockerfile used to test proot-rs? And is it related to [#6 (comment)](https://github.com/proot-me/proot-rs/issues/6#issuecomment-846402777) ?

Yes. We can build in the first stage, and then test in the second.

**Comment by KB5201314** [comment]
Sorry, there may be a problem with my expression. For testing, I think we can download the busybox rootfs tarball and unzip it into a directory. This way we can use it as a new rootfs for testing proot-rs. Maybe we just need a bash script to do this

Like this.
```
curl -o $rootfs_tarball -L -C - "https://github.com/docker-library/busybox/raw/dist-${arch}/stable/glibc/busybox.tar.xz" 
tar -C $rootfs -xf $rootfs_tarball
proot-rs --rootfs $rootfs /bin/sh # or we can run `cargo test`
```

**Comment by oxr463** [comment]
> Sorry, there may be a problem with my expression. For testing, I think we can download the busybox rootfs tarball and unzip it into a directory. This way we can use it as a new rootfs for testing proot-rs. Maybe we just need a bash script to do this
> 
> Like this.
> 
> ```
> curl -o $rootfs_tarball -L -C - "https://github.com/docker-library/busybox/raw/dist-${arch}/stable/glibc/busybox.tar.xz" 
> tar -C $rootfs -xf $rootfs_tarball
> proot-rs --rootfs $rootfs /bin/sh # or we can run `cargo test`
> ```

That makes sense. Do we need something like this to run the script before running the tests? https://github.com/sagiegurari/cargo-make

**Comment by KB5201314** [comment]
> > Sorry, there may be a problem with my expression. For testing, I think we can download the busybox rootfs tarball and unzip it into a directory. This way we can use it as a new rootfs for testing proot-rs. Maybe we just need a bash script to do this
> > Like this.
> > ```
> > curl -o $rootfs_tarball -L -C - "https://github.com/docker-library/busybox/raw/dist-${arch}/stable/glibc/busybox.tar.xz" 
> > tar -C $rootfs -xf $rootfs_tarball
> > proot-rs --rootfs $rootfs /bin/sh # or we can run `cargo test`
> > ```
> 
> That makes sense. Do we need something like this to run the script before running the tests? https://github.com/sagiegurari/cargo-make

That's a good idea, I think we can try this

**Pull request merged**
