### PR TITLE
[build] syscall is deprecated. use sc

### PR DESCRIPTION
**Pull request by ritzk**
syscall has been deprecated[1] in favor of sc[2]

[1] https://github.com/kmcallister/syscall.rs/issues/28
[2] https://crates.io/crates/sc

### CODE REVIEW

**Comment by oxr463** [comment]
@panicbit can you review this PR?

**Review by panicbit — APPROVED** [review]
Looks good to me. There are a few concerns I have regarding code that is not part of this PR, but since I am not very familiar with the codebase yet it's a good oportunaty for me to take care of them once I do my sweep over the codebase.

**Comment by panicbit** [comment]
I still have to look into why the tests are failing, but despite them failing, this PR is necessary to get the project to even compile on recent versions of Rust.

**Comment by oxr463** [comment]
Closing in favor of https://github.com/proot-me/proot-rs/pull/12

**Pull request closed without merging**
